//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeUniProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public AppUser()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int AppUserID { get; set; }
        public string AppUserName { get; set; }
        public string AppUserPass { get; set; }
        public bool IsActive { get; set; }
        public byte AppUserType { get; set; }
    
        public virtual ICollection<Bid> Bids { get; set; }
    }
}
