//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeUniProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public long BidID { get; set; }
        public int DebitorID { get; set; }
        public byte JobExperience { get; set; }
        public System.DateTime BidDate { get; set; }
        public int BidCreator { get; set; }
        public decimal Amount { get; set; }
        public byte BidStatus { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Debitor Debitor { get; set; }
    }
}
